### ISSUE TITLE
Non-route Popups Don't Work in Safari

### ISSUE THREAD

**Issue by pqhf5kd** [nekromoff/bicycle-master-plan#20]
Popups for routes work fine in Safari 14.0.2 on macOS 11.1
Popups for other features, racks, repair stands, photos, warnings, do not appear.

**Comment by nekromoff** [comment]
Due to this Leaflet bug:
https://github.com/Leaflet/Leaflet/issues/7255

Also see workaround suggestion using `tap: false`:
https://github.com/domoritz/leaflet-locatecontrol/issues/280
