### ISSUE TITLE
Suggestion - mark highway=crossing

### ISSUE THREAD

**Issue by pqhf5kd** [nekromoff/bicycle-master-plan#23]
I believe it would be useful to visualise crossings that allow bicycles to be ridden across. 

Here is an example

https://www.openstreetmap.org/node/273179081

This could be accomplished with a new marker layer. Green dots could be placed on nodes that are tagged with highway=crossing and bicycle=yes or bicycle=designated. Red dots could be placed on nodes that are tagged with highway=crossing and bicycle=no.

**Comment by nekromoff** [comment]
Please, add this to your city specific stylesheet under `cities/sk-kosice.css` via a pull request.
