### ISSUE TITLE
MTB-Scale

### ISSUE THREAD

**Issue by pqhf5kd** [nekromoff/bicycle-master-plan#24]
The CSS style for MTB-Scale is currently: 
`.bicycle-yes.surface-gravel, .bicycle-yes.surface-dirt, .bicycle-yes.surface-grass, .highway-cycleway.surface-gravel, .highway-track.bicycle-yes `

I suggest adding the following tags:
` .bicycle-designated.surface-gravel, .bicycle-designated.surface-dirt, .bicycle-designated.surface-grass, .highway-track.bicycle-designated `

And possibly: 
` .bicycle-designated.surface-unpaved, .bicycle-yes.surface-unpaved`
The definition of unpaved on the OSM wiki is vague and it is recommend to use a more precise tag:
> A feature that is predominantly unsealed (unpaved); i.e., it has a loose covering ranging from compacted stone chippings to earth. Unpaved roads may, in aerial imagery, show evidence of water along their course; in such circumstances, the waterway should not be tagged as a stream, though it might appear as such. This value gives only a rough description; use a more precise value if possible.

**Comment by nekromoff** [comment]
added to city specific stylesheets
