### ISSUE TITLE
route=hiking

### ISSUE THREAD

**Issue by pqhf5kd** [nekromoff/bicycle-master-plan#25]
https://mapa.cyklokoalicia.sk/kosice/public/#l4,5|z14|c48.71719,21.16077|p4-353288218

In Kosice, a hiking route is being rendered green (Značené (v premávke)). The route has no bicycle related tags. I believe it is because of the LCN tag.

I suggest adding:
`.route-hiking:not(.bicycle-yes):not(.bicycle-designated)` 
to [line 370 ](https://github.com/nekromoff/bicycle-master-plan/blob/master/public/css/main.css#L370) in main.css.

I hope the not syntax is correct. I don't have a way example tagged as route=hiking & bicycle=yes but I imagine it could exist.

**Comment by nekromoff** [comment]
added to city specific stylesheets
