### ISSUE TITLE
Right click - add pin - active even if the specific layer is off

### ISSUE THREAD

**Issue by AdrianChren** [nekromoff/bicycle-master-plan#32]
The right click option (or on mobile holding one point on screen) is active, even when the layer "tipy a upozornenia" is not active. In that case, if the layer is not checkboxed, option for adding pin should be non-active. In case of checkboxed layer, option for adding pin should be active.

**Comment by nekromoff** [comment]
After thinking about this for a bit, this is more of a feature than a bug. Editable layer can be turned off, but adding a marker is always just a click/tap away. So closing.
